/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PageFooter: typeof import('./src/components/Common/PageFooter.vue')['default']
    PageHeader: typeof import('./src/components/Common/PageHeader.vue')['default']
    PageSideBar: typeof import('./src/components/Common/PageSideBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
